### ISSUE TITLE
Support the packages that use `test/` as a separate environment

### ISSUE THREAD

**Issue by tansongchen** [julia-actions/julia-runtest#14]
Currently the `PkgTemplates.jl` has an [option](https://invenia.github.io/PkgTemplates.jl/stable/user/#Default-Plugins-1) to make `test/` directory a separate environment in order to manage its own dependents (so the main package doesn't need `Test` as extras). However, this action execute the tests at the root directory and cannot be overloaded. Should we create a new input for that?

**Comment by SaschaMann** [comment]
Sounds good to me. Is there anything needed other than setting `--project=test/`?

**Comment by tansongchen** [comment]
Hi I think I misunderstand some point yesterday, the current version of this action should be fine.

Firstly, as [Pkg.jl](https://julialang.github.io/Pkg.jl/v1/creating-packages/) mentions, one can still use `Pkg.test()` to test a package even if `test/` is a separate environment. But this is a feature for Julia v1.2+ only.

Yesterday my CI config (generated from `PkgTemplates.jl`) contained Julia v1.0 so the CI failed, and I thought it was a matter of this action... But today when I remove v1.0 the remaining tests are working well, see [a test repo](https://github.com/tansongchen/TSD.jl/actions/runs/206399753).

Thanks and I will close this.
