### ISSUE TITLE
ERROR: AssertionError: sourcepath !== nothing

### ISSUE THREAD

**Issue by maartenvd** [julia-actions/julia-runtest#18]
It is unclear to me why this run fails

https://github.com/maartenvd/MPSKit.jl/runs/1144160556

**Comment by SaschaMann** [comment]
Good question, I have no idea. Does it work locally?

**Comment by maartenvd** [comment]
yes, and I never had any issues before

**Comment by DilumAluthge** [comment]
You have a circular dependency. MPSKit depends on MPSKitModels, but MPSKitModels depends on MPSKit. This is not expected to work.

The fact that it appeared to work on older versions of Julia is a bug.

**Comment by DilumAluthge** [comment]
To elaborate: if PkgA is listed in the [deps] section of PkgB's Project.toml file, then PkgB cannot be listed in the [deps] section of PkgA's Project.toml file.

**Comment by DilumAluthge** [comment]
In your case, MPSKitModels is listed in the [deps] section of MPSKit's Project.toml file: https://github.com/maartenvd/MPSKit.jl/blob/master/Project.toml

But MPSKit is listed in the [deps] section of MPSKitModels's Project.toml file: https://github.com/maartenvd/MPSKitModels.jl/blob/master/Project.toml
