### ISSUE TITLE
Setup CI for julia-* actions

### ISSUE THREAD

**Issue by SaschaMann** [julia-actions/julia-runtest#25]
With an increase of options for running this action as well as more and more people using GHA for their package CI, I'd prefer having at least some form of automated tests for these actions. A single typo that isn't caught during code review could break builds across hundreds of repos at this point.

My idea for a basic automated end-to-end test:

1. Add a workflow that mirrors the default package CI workflow.
1. Instead of checking out the local repo, check out Example.jl in the main working directory.
1. Clone the action repo to `.github/actions/julia-runtest` and refer to it via `uses: ./.github/actions/julia-runtest`
1. Somehow verify that the actions actually did what they were meant to do.

The 4th point is the difficult one. My idea would be adding a test to the package itself that changes some file so that the test workflow could check that the file has been modified. Perhaps we could also capture the output of the tests within `runtests.jl` and then print that to a file? Both options are somewhat hacky and fragile, perhaps there's a better way. @DilumAluthge do you have an idea?

---

This equally applies to julia-buildpkg etc. but I don't want to duplicate the issues.

**Comment by DilumAluthge** [comment]
> My idea would be adding a test to the package itself that changes some file so that the test workflow could check that the file has been modified.

I think this is the easiest thing to start with. We can add fancier stuff later, but this will get us started for now.

**Comment by DilumAluthge** [comment]
> This equally applies to julia-buildpkg etc.

Similarly for this part, we could have a `deps/build.jl` script that creates a new file somewhere. And then we check for its creation before and after.

**Comment by SaschaMann** [comment]
julia-buildpkg and -runtest are the most important ones. The others haven't seen as many changes, so we can add the file if/when we need it.

**Comment by DilumAluthge** [comment]
SGTM.
