### ISSUE TITLE
Use julia as shell instead of bash

### ISSUE THREAD

**Issue by giordano** [julia-actions/julia-runtest#35]
I'm trying to run CI on Alpine with the [docker image](https://hub.docker.com/_/julia), but it fails because the julia images on Docker don't have bash.  Can we use `julia` as shell instead?  That should Just Work:tm: on any operating system

*Edit*:
https://github.com/julia-actions/julia-runtest/blob/b32c73084a913834335f8ff0ce6f6cad610a6fcf/action.yml#L46-L56
looks hard to do in a julia shell :persevere:

**Comment by SaschaMann** [comment]
Does the image have `sh` at least? We could probably switch to that.

**Comment by giordano** [comment]
Yes, there is `sh` but as I mentioned in slack `sh` isn't available for Windows

**Comment by SaschaMann** [comment]
Ah, sorry, haven't read Slack yet. I guess we could rewrite it as Julia script and start the test process via `run()`? I wonder if that slows down the action, though.

**Comment by giordano** [comment]
Alternatively, have two identical steps, one run with bash on windows and the other one for all other systems with sh. It's a gross solution though, with code duplication.... (the idea of your script would at least reduce duplication)

**Comment by SaschaMann** [comment]
If I remember correctly, composite actions don't allow conditional steps. So we'd have to check the environment within the script and run into the same situation again where there's no universal shell.

**Comment by giordano** [comment]
Can the shell be
```
${{ inputs.prefix }} julia...
```
😅

**Comment by SaschaMann** [comment]
Let's find out: https://github.com/julia-actions/julia-runtest/pull/36

**Comment by SaschaMann** [comment]
Unfortunately not:

```
Error: /home/runner/work/julia-runtest/julia-runtest/./.github/actions/julia-runtest/action.yml (Line: 49, Col: 14):
Error: /home/runner/work/julia-runtest/julia-runtest/./.github/actions/julia-runtest/action.yml (Line: 49, Col: 14): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.prefix
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/julia-runtest/julia-runtest/./.github/actions/julia-runtest/action.yml (Line: 49, Col: 14): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.prefix
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateCon[...]
Error: Fail to load /home/runner/work/julia-runtest/julia-runtest/./.github/actions/julia-runtest/action.yml
```

**Comment by giordano** [comment]
Dang... ok, I don't see many other options... I don't think using Julia to run Julia is a great solution, for performance reasons.  Thanks for the help!
